import { test, expect, describe, afterEach } from "bun:test";
import * as fs from "fs";
import * as path from "path";
import { gitSpawn } from "../../api/utils";
import { cleanupRepos, git, tempProject, tempRepo, tempTask } from "../../../test/git-repo";
import { taskDir } from "../agent/spawn";
import { createWorktree } from "./create";
import { WorktreeError } from "./errors";
import { restoreWorktree } from "./restore";
import { applyWip, dropWip, readWip, snapshotWip, wipRefFor } from "./wip";

afterEach(cleanupRepos);

/** `git status --porcelain`, as lines, so a test can state the working state
 * it expects rather than a diff of a string.
 *
 * Not through the `git` helper: that one trims, and the first two columns of a
 * porcelain line are the status itself — ` M` is "modified, not staged" and
 * `M ` is "modified and staged", so a trim turns the assertion that tells them
 * apart into one that cannot. */
async function status(dir: string): Promise<string[]> {
  const { stdout } = await gitSpawn(dir, ["status", "--porcelain"]);
  return stdout.split("\n").filter(Boolean).sort();
}

/** A task with a checkout, dirty in all four ways that behave differently
 * across a snapshot: a tracked file edited, a tracked file deleted, a file git
 * has never seen, and a file the project ignores. */
async function dirtyTask(root: string) {
  const project = tempProject(root);
  const task = tempTask("Snapshot me");
  const created = await createWorktree(project, task, "main");
  const at = (p: string) => path.join(created.worktreePath, p);

  fs.writeFileSync(at("README.md"), "edited in the worktree\n");
  fs.writeFileSync(at("doomed.txt"), "delete me\n");
  fs.writeFileSync(at(".gitignore"), "ignored/\n");
  await git(created.worktreePath, "add", "-A");
  await git(created.worktreePath, "commit", "-qm", "a commit on the task's branch");
  fs.writeFileSync(at("README.md"), "dirty\n");
  fs.rmSync(at("doomed.txt"));
  fs.writeFileSync(at("untracked.txt"), "never seen by git\n");
  fs.mkdirSync(at("ignored"));
  fs.writeFileSync(at("ignored/build.out"), "regenerated by setup\n");

  return { project, task, created, at };
}

describe("snapshotWip", () => {
  // AC #1. The premise of evicting a dirty tree is that taking the snapshot
  // costs the user nothing — so the thing to assert is not what the ref says,
  // it is that everything else is exactly where it was.
  test("writes the ref without touching the working tree, the index, or the branch", async () => {
    const { root } = await tempRepo();
    const { task, created } = await dirtyTask(root);
    // Something staged as well, so the index has a state to be disturbed.
    await git(created.worktreePath, "add", "untracked.txt");
    const before = await status(created.worktreePath);
    const head = await git(created.worktreePath, "rev-parse", "HEAD");
    const branchTip = await git(root, "rev-parse", created.branch);

    const snapshot = await snapshotWip({ id: task.id, worktreePath: created.worktreePath });

    expect(snapshot.ref).toBe(`refs/codetoaster/wip/${task.id}`);
    expect(await git(root, "rev-parse", snapshot.ref)).toBe(snapshot.commit);
    expect(await status(created.worktreePath)).toEqual(before);
    expect(await git(created.worktreePath, "rev-parse", "HEAD")).toBe(head);
    expect(await git(root, "rev-parse", created.branch)).toBe(branchTip);
    // The snapshot hangs off HEAD and moves nothing: one commit reachable from
    // the branch, and the branch still where it was.
    expect((await readWip(root, task.id))?.parent).toBe(head);
    // And the scratch index is not left behind for the next snapshot to read
    // as a starting point. Asserted where it actually lives — the task's own
    // directory, deliberately outside the checkout — since a path inside the
    // repository is one the snapshot never writes and the assertion would hold
    // however badly it leaked.
    expect(fs.existsSync(path.join(taskDir(task.id), "wip.index"))).toBe(false);
  });

  // The identity is set explicitly because `commit-tree` refuses to run
  // without one — `user.useConfigOnly` is a real setting — and because the
  // user did not write this commit.
  test("commits as codetoaster, not as the user", async () => {
    const { root } = await tempRepo();
    const { task, created } = await dirtyTask(root);

    const snapshot = await snapshotWip({ id: task.id, worktreePath: created.worktreePath });

    expect(await git(root, "show", "-s", "--format=%an <%ae>", snapshot.commit))
      .toBe("codetoaster <wip@codetoaster.invalid>");
  });

  // AC #5, first half.
  test("re-snapshotting moves the ref to the newer commit", async () => {
    const { root } = await tempRepo();
    const { task, created } = await dirtyTask(root);

    const first = await snapshotWip({ id: task.id, worktreePath: created.worktreePath });
    fs.writeFileSync(path.join(created.worktreePath, "README.md"), "dirtier\n");
    const second = await snapshotWip({ id: task.id, worktreePath: created.worktreePath });

    expect(second.commit).not.toBe(first.commit);
    expect(await git(root, "rev-parse", wipRefFor(task.id))).toBe(second.commit);
  });

  // AC #5, second half. The ref is the only thing keeping the objects alive:
  // `refs/codetoaster/*` gets no reflog, since git only logs updates under
  // `refs/heads`, `refs/remotes`, `refs/notes` and HEAD.
  test("dropping the ref leaves the objects collectable", async () => {
    const { root } = await tempRepo();
    const { task, created } = await dirtyTask(root);
    const snapshot = await snapshotWip({ id: task.id, worktreePath: created.worktreePath });

    await dropWip(root, task.id);
    // The worktree still holds the same content, and a checkout is a gc root —
    // so it has to go before the objects can be unreachable.
    await git(root, "worktree", "remove", "--force", created.worktreePath);
    await git(root, "reflog", "expire", "--expire=now", "--all");
    await git(root, "gc", "--prune=now", "-q");

    expect(await readWip(root, task.id)).toBeNull();
    const { exitCode } = await gitSpawn(root, ["cat-file", "-e", snapshot.commit]);
    expect(exitCode).not.toBe(0);
  });

  test("dropping a ref that is not there is not an error", async () => {
    const { root } = await tempRepo();
    await dropWip(root, "task-never-snapshotted");
    expect(await readWip(root, "task-never-snapshotted")).toBeNull();
  });
});

describe("restoreWorktree", () => {
  // AC #2, the round trip the whole tier rests on. Each of the three kinds of
  // dirt comes back as its own kind: an edit as an edit, a deletion as a
  // deletion, an untracked file as untracked — and none of it staged, which is
  // what `reset --mixed` after `read-tree --reset` buys.
  test("brings modified, deleted and untracked files back as they were", async () => {
    const { root } = await tempRepo();
    const { project, task, created } = await dirtyTask(root);
    const before = await status(created.worktreePath);
    expect(before).toEqual([" D doomed.txt", " M README.md", "?? untracked.txt"]);

    await snapshotWip({ id: task.id, worktreePath: created.worktreePath });
    await git(root, "worktree", "remove", "--force", created.worktreePath);
    await git(root, "worktree", "prune");

    const restored = await restoreWorktree(
      { root: root, worktreeCopy: project.worktree_copy },
      { id: task.id, branch: created.branch, worktreePath: created.worktreePath },
    );

    expect(restored.wip).toBe("applied");
    expect(restored.worktreePath).toBe(created.worktreePath);
    expect(await status(restored.worktreePath)).toEqual(before);
    expect(fs.readFileSync(path.join(restored.worktreePath, "README.md"), "utf8")).toBe("dirty\n");
    // Index at HEAD, so nothing reads as staged: `diff --cached` is empty.
    expect(await git(restored.worktreePath, "diff", "--cached", "--name-only")).toBe("");
  });

  // §5.6's documented simplifications, asserted rather than assumed: one tree
  // cannot carry the staged/unstaged split, and `add -A` honours `.gitignore`.
  // Both are why `setup_command` and `worktree_copy` are load-bearing.
  test("flattens the index and does not carry ignored files", async () => {
    const { root } = await tempRepo();
    const { project, task, created } = await dirtyTask(root);
    await git(created.worktreePath, "add", "untracked.txt");
    expect(await status(created.worktreePath)).toContain("A  untracked.txt");

    await snapshotWip({ id: task.id, worktreePath: created.worktreePath });
    await git(root, "worktree", "remove", "--force", created.worktreePath);
    const restored = await restoreWorktree(
      { root: root, worktreeCopy: project.worktree_copy },
      { id: task.id, branch: created.branch, worktreePath: created.worktreePath },
    );

    expect(await status(restored.worktreePath)).toContain("?? untracked.txt");
    expect(fs.existsSync(path.join(restored.worktreePath, "ignored/build.out"))).toBe(false);
  });

  // AC #4.
  test("restores a clean checkout for a task that has no snapshot", async () => {
    const { root } = await tempRepo();
    const project = tempProject(root);
    const task = tempTask("Never evicted dirty");
    const created = await createWorktree(project, task, "main");
    await git(root, "worktree", "remove", "--force", created.worktreePath);

    const restored = await restoreWorktree(
      { root: root, worktreeCopy: project.worktree_copy },
      { id: task.id, branch: created.branch, worktreePath: created.worktreePath },
    );

    expect(restored.wip).toBe("none");
    expect(restored.staleRef).toBeUndefined();
    expect(await status(restored.worktreePath)).toEqual([]);
    expect(await git(restored.worktreePath, "rev-parse", "--abbrev-ref", "HEAD"))
      .toBe(created.branch);
  });

  // AC #3, and the reason the guard exists at all. The branch is the task's
  // but it is not ours alone: the user still has the repository and can commit
  // to it from anywhere. Applying a snapshot taken against the old tip would
  // write the old version of every tracked file over the new commit's, and say
  // nothing — the tree would just look plausibly dirty.
  test("refuses a snapshot whose parent is no longer the branch tip", async () => {
    const { root } = await tempRepo();
    const { project, task, created } = await dirtyTask(root);
    await snapshotWip({ id: task.id, worktreePath: created.worktreePath });
    const snapshot = wipRefFor(task.id);
    await git(root, "worktree", "remove", "--force", created.worktreePath);

    // The user commits to the task's branch from the main checkout while the
    // task is evicted.
    await git(root, "checkout", "-q", created.branch);
    fs.writeFileSync(path.join(root, "README.md"), "committed elsewhere\n");
    await git(root, "commit", "-qam", "work done outside the task");
    const newTip = await git(root, "rev-parse", "HEAD");
    await git(root, "checkout", "-q", "main");

    const restored = await restoreWorktree(
      { root: root, worktreeCopy: project.worktree_copy },
      { id: task.id, branch: created.branch, worktreePath: created.worktreePath },
    );

    expect(restored.wip).toBe("stale");
    // Kept, not discarded: the choice is the user's, and nothing is lost while
    // they make it.
    expect(restored.staleRef).toBe(snapshot);
    expect(await readWip(root, task.id)).not.toBeNull();
    // The newer commit survived intact, which is the whole point.
    expect(await git(restored.worktreePath, "rev-parse", "HEAD")).toBe(newTip);
    expect(fs.readFileSync(path.join(restored.worktreePath, "README.md"), "utf8"))
      .toBe("committed elsewhere\n");
    expect(await status(restored.worktreePath)).toEqual([]);
  });

  // The "apply stale WIP" arm of that card. Refusing has to leave something
  // the user can still choose, or it is just a slower way of losing the work.
  test("a stale snapshot can still be applied deliberately", async () => {
    const { root } = await tempRepo();
    const { project, task, created } = await dirtyTask(root);
    await snapshotWip({ id: task.id, worktreePath: created.worktreePath });
    await git(root, "worktree", "remove", "--force", created.worktreePath);
    await git(root, "checkout", "-q", created.branch);
    fs.writeFileSync(path.join(root, "NEW.md"), "elsewhere\n");
    await git(root, "add", "-A");
    await git(root, "commit", "-qm", "work done outside the task");
    await git(root, "checkout", "-q", "main");

    const restored = await restoreWorktree(
      { root: root, worktreeCopy: project.worktree_copy },
      { id: task.id, branch: created.branch, worktreePath: created.worktreePath },
    );
    expect(restored.wip).toBe("stale");
    await applyWip(restored.worktreePath, restored.staleRef!);

    expect(fs.readFileSync(path.join(restored.worktreePath, "README.md"), "utf8")).toBe("dirty\n");
    expect(await status(restored.worktreePath)).toContain("?? untracked.txt");
  });

  // Not a generic add failure: the work is safe in the ref, and what is
  // missing is a decision about where it goes (§5.6).
  test("names a deleted branch as its own failure", async () => {
    const { root } = await tempRepo();
    const { project, task, created } = await dirtyTask(root);
    await snapshotWip({ id: task.id, worktreePath: created.worktreePath });
    await git(root, "worktree", "remove", "--force", created.worktreePath);
    await git(root, "branch", "-D", created.branch);

    const error = await restoreWorktree(
      { root: root, worktreeCopy: project.worktree_copy },
      { id: task.id, branch: created.branch, worktreePath: created.worktreePath },
    ).catch((e) => e);

    expect(error).toBeInstanceOf(WorktreeError);
    expect(error.kind).toBe("branch-missing");
    // Refused before anything was created, so a retry after the user restores
    // the branch is not blocked by a leftover directory.
    expect(fs.existsSync(created.worktreePath)).toBe(false);
    expect(await readWip(root, task.id)).not.toBeNull();
  });

  // The other half of that registration case, and why it is a `worktree prune`
  // rather than `--force`: `--force` clears the stale registration *and* the
  // safeguard against a branch that is checked out somewhere else. The branch
  // is the task's but the repository is the user's, and forcing past that would
  // give one branch two working trees — the agent's next commit would move HEAD
  // under the user's own checkout and their tree would read as changes nobody
  // made. Refusing, with git's own account of why, is the honest answer.
  test("refuses a branch the user has checked out somewhere else", async () => {
    const { root } = await tempRepo();
    const { project, task, created } = await dirtyTask(root);
    await snapshotWip({ id: task.id, worktreePath: created.worktreePath });
    await git(root, "worktree", "remove", "--force", created.worktreePath);
    await git(root, "checkout", "-q", created.branch);

    const error = await restoreWorktree(
      { root: root, worktreeCopy: project.worktree_copy },
      { id: task.id, branch: created.branch, worktreePath: created.worktreePath },
    ).catch((e) => e);

    expect(error).toBeInstanceOf(WorktreeError);
    expect(error.kind).toBe("worktree-add-failed");
    expect(error.stderr).toContain("already used by worktree");
    // Nothing half-made left at the path, so the restore is retryable the
    // moment the user moves off the branch.
    expect(fs.existsSync(created.worktreePath)).toBe(false);
    expect(await readWip(root, task.id)).not.toBeNull();
  });

  // What `rm -rf` on a worktree leaves: git still has the registration, and
  // `worktree add` refuses the path outright without `--force`. The path is
  // fixed by the task's id and cannot be moved away from, so this is the
  // difference between a restorable task and a permanently broken one.
  test("restores over a registration whose directory was removed by hand", async () => {
    const { root } = await tempRepo();
    const { project, task, created } = await dirtyTask(root);
    await snapshotWip({ id: task.id, worktreePath: created.worktreePath });
    fs.rmSync(created.worktreePath, { recursive: true, force: true });

    const restored = await restoreWorktree(
      { root: root, worktreeCopy: project.worktree_copy },
      { id: task.id, branch: created.branch, worktreePath: created.worktreePath },
    );

    expect(restored.wip).toBe("applied");
    expect(fs.readFileSync(path.join(restored.worktreePath, "README.md"), "utf8")).toBe("dirty\n");
  });
});

describe("restoreWorktree and the project's files", () => {
  // §5.6's load-bearing pair. `git add -A` honours `.gitignore`, so an ignored
  // file cannot reach the snapshot — which makes `worktree_copy` the only thing
  // that puts it back, and makes this the test that it is actually run.
  test("re-copies worktree_copy entries a snapshot could not carry", async () => {
    const { root } = await tempRepo();
    fs.writeFileSync(path.join(root, ".gitignore"), ".env\n");
    fs.writeFileSync(path.join(root, ".env"), "SECRET=1\n");
    await git(root, "add", ".gitignore");
    await git(root, "commit", "-qm", "ignore .env");
    const project = { ...tempProject(root), worktree_copy: ".env" };
    const task = tempTask("Needs its dotenv");
    const created = await createWorktree(project, task, "main");
    expect(fs.existsSync(path.join(created.worktreePath, ".env"))).toBe(true);

    await snapshotWip({ id: task.id, worktreePath: created.worktreePath });
    await git(root, "worktree", "remove", "--force", created.worktreePath);

    const restored = await restoreWorktree(
      { root: root, worktreeCopy: project.worktree_copy },
      { id: task.id, branch: created.branch, worktreePath: created.worktreePath },
    );

    expect(restored.copied).toEqual([".env"]);
    expect(fs.readFileSync(path.join(restored.worktreePath, ".env"), "utf8")).toBe("SECRET=1\n");
  });

  // The ordering decision: a copy list may name a tracked path, and then the
  // template and the snapshot both have an opinion about it. The snapshot is
  // the user's work, so the copy goes first and `read-tree --reset` wins.
  test("lets the snapshot win over a copy of a tracked file", async () => {
    const { root } = await tempRepo();
    const project = { ...tempProject(root), worktree_copy: "README.md" };
    const task = tempTask("Overlapping copy");
    const created = await createWorktree(project, task, "main");
    fs.writeFileSync(path.join(created.worktreePath, "README.md"), "the user's work\n");

    await snapshotWip({ id: task.id, worktreePath: created.worktreePath });
    await git(root, "worktree", "remove", "--force", created.worktreePath);

    const restored = await restoreWorktree(
      { root: root, worktreeCopy: project.worktree_copy },
      { id: task.id, branch: created.branch, worktreePath: created.worktreePath },
    );

    expect(restored.wip).toBe("applied");
    expect(fs.readFileSync(path.join(restored.worktreePath, "README.md"), "utf8"))
      .toBe("the user's work\n");
  });
});
